### PR TITLE
Add Yusril as mentee

### PR DESCRIPTION
**Pull request by usereall**
Please merge my pull request as a mentee in 2021-academy

### CODE REVIEW

**Comment by adhiiimf** [comment]
thanks for **PR** (Pull Request), but in description you shouldn't tag reviewer again 'cause in **PR** you've feature add review to review your **PR** and the reviewer automatically get notif about this **PR**

and don't forget to describe about your **PR** to tell everyone the purpose and more relate about your **PR**

Thankyou

**Comment by adhiiimf** [comment]
> thanks for **PR** (Pull Request), but in description you shouldn't tag reviewer again 'cause in **PR** you've feature add review to review your **PR** and the reviewer automatically get notif about this **PR**
> 
> and don't forget to describe about your **PR** to tell everyone the purpose and more relate to your **PR**
> 
> Thankyou

Oh ya don't forget to add reviewer from daskom development or devkom as you know to review this **PR** to get approval 👍

**Comment by usereall** [comment]
tadi saya salah memahami bang, saya kira add reviewernya dengan cara di tag dan karena ga ada daskom development, jadi saya ngetag bang fai

**Comment by usereall** [comment]
I've revised the description section and added daskom development as a reviewers

**Review by fakhrip — APPROVED** [review]
Sipp dah bener yusril, lanjut ke challenge ke 2 ya

**Pull request merged**
