### PR TITLE
add website link

### LINKED ISSUE #20: RUS

### PR DESCRIPTION
**Pull request by rusmajunior**
Please approve my pull request, i added my website link in readme
fix #20

### CODE REVIEW

**Review by fakhrip — APPROVED** [review]
Mantap, good job rusma

**Comment by fakhrip** [comment]
> Please approve my pull request, i added my website link in readme
> fix #20

But please later on, do not put the `Please approve` stuff, we will definitely approve it as long as everything is correct :wink:

**Comment by rusmajunior** [comment]
> > Please approve my pull request, i added my website link in readme
> > fix #20
> 
> But please later on, do not put the `Please approve` stuff, we will definitely approve it as long as everything is correct 😉

siaapp bangg terima kasih

**Comment by rusmajunior** [comment]
> Mantap, good job rusma

abisni diapain bang?

**Comment by fakhrip** [comment]
> > Mantap, good job rusma
> 
> abisni diapain bang?

Kita tunggu yang lainnya kelar ya wkwk, ntar kita kayak biasa meet dulu buat bahas selanjutnya gimana

**Pull request merged**
